apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: adservice-grpc-api
  description: gRPC API exposed by adservice and consumed by frontend.
spec:
  type: grpc
  lifecycle: production
  owner: group:default/team-platform
  system: online-boutique
  definition: |
    service AdService {
      rpc GetAds(AdRequest) returns (AdResponse);
    }
