apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: recommendationservice-grpc-api
  description: gRPC API used to get product recommendations.
spec:
  type: grpc
  lifecycle: production
  owner: group:default/team-platform
  system: online-boutique
  definition: |
    service RecommendationService {
      rpc ListRecommendations(ListRecommendationsRequest) returns (ListRecommendationsResponse);
    }
