apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: shippingservice
  description: Service that quotes and ships orders.
  annotations:
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-id: shippingservice
spec:
  type: service
  lifecycle: production
  owner: group:default/team-platform
  system: online-boutique
  providesApis:
    - api:default/shippingservice-grpc-api
  dependsOn:
    - resource:default/online-boutique-namespace
