apiVersion: v1
kind: ConfigMap
metadata:
  name: backstage-v3-runtime-config
  namespace: backstage
data:
  BACKSTAGE_BASE_URL: http://localhost:7007
  POSTGRES_HOST: backstage-postgresql-rw
  POSTGRES_PORT: "5432"
  POSTGRES_DB: backstage
  GITEA_HOST: gitea:3000
  GITEA_BASE_URL: http://gitea:3000
  GITEA_CATALOG_INDEX_URL: http://gitea:3000/root/repo-infra/src/branch/main/backstage/catalog/index.yaml
  ARGOCD_URL: http://argocd-server.argocd.svc.cluster.local
  PROMETHEUS_API_URL: http://prometheus-server.prometheus.svc.cluster.local/api/v1/
  PROMETHEUS_UI_URL: http://prometheus-server.prometheus.svc.cluster.local
  DOCKER_HUB_URL: https://hub.docker.com