apiVersion: v1
kind: Secret
metadata:
  name: backstage-v3-secrets
  namespace: backstage
type: Opaque
stringData:
  POSTGRES_USER: backstage
  POSTGRES_PASSWORD: backstage
  ARGOCD_USERNAME: admin
  ARGOCD_PASSWORD: 7f4jqsARrkic5Ail
  GITEA_TOKEN: 5aa6b4a106072253d2f11f914ca6b91442de533a